name: crazyfeyn_sort_groups
description: A starting point for Dart libraries or applications. You can chech it out
version: 1.0.0
repository: https://github.com/crazyfeyn/month_5

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
