name: crazyfeyn_sort_groups
description: Uzbekistan, Najot talim, crazyfeyn. These are my main infos. Happ yammy You can chech it out, this is my package for task
version: 1.2.0
repository: https://github.com/crazyfeyn/month_5

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
