name: crazyfeyns_first_package
description: A simple package that provides utility functions for string manipulation in Dart.
version: 1.0.0
repository: https://github.com/crazyfeyn/month_5.git

environment:
  sdk: ^3.4.4

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
