name: crazyfeyns_first_package
description: crazyfeyns_first_package is a simple Dart package designed to provide utility functions for string manipulation. This package aims to simplify common string operations, making it easier for developers to handle and manipulate strings in their Dart applications.
version: 1.0.4
repository: https://github.com/crazyfeyn/month_5.git

environment:
  sdk: ^3.4.4

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
